plugins:
  - tag: global_dns
    type: forward
    args:
      concurrent: 2
      upstreams:
        - tag: "Google DOT"
          addr: 'tls://dns.google'
          dial_addr: 8.8.8.8
          enable_pipeline: true
        - tag: "Google DOT2"
          addr: "tls://dns.google"
          dial_addr: 8.8.4.4
          enable_pipeline: true
  - tag: cn_dns
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: "DNSPod"
          addr: 'tls://dot.pub'
          bootstrap: "223.5.5.5"
          enable_pipeline: true
        - tag: "AliDNS"
          addr: "https://dns.alidns.com/dns-query"
          bootstrap: "119.29.29.29"