plugins:
  - tag: handle_ecs
    type: ecs_handler
    args:
      forward: true
      send: true
      mask4: 32
      mask6: 48
  - tag: cloudflare
    type: sequence
    args:
      - matches:
        - "resp_ip $cloudflare_ip"
        - "qtype 1"
        exec: "black_hole $cf_ip4_prefer"
      - matches:
        - "resp_ip $cloudflare_ip"
        - "qtype 28"
        exec: "black_hole $cf_ip6_prefer" 
  - tag: cn_resolver
    type: sequence
    args:
      - exec: $cn_dns
      - matches:
        - "resp_ip $blacklist"
        exec: drop_resp
      - exec: query_summary $cn_dns
      - exec: accept
  - tag: global_resolver
    type: sequence
    args:
      - exec: $global_dns
      - matches:
        - "resp_ip $blacklist"
        exec: drop_resp
      - exec: query_summary $global_dns
  - tag: fallback
    type: fallback
    args:
      primary: cn_resolver
      secondary: global_resolver
      threshold: 20000
      always_standby: true
  - tag: main
    type: sequence
    args:
      - exec: $handle_ecs
      - exec: forward_edns0opt 10 15
      - matches:
        - qname $cn_domain
        exec: $cn_resolver
      - matches: has_resp
        exec: accept
      - exec: $global_resolver
      - matches:
        - resp_ip $cn_ip
        exec: $cn_resolver
      - matches: 
        - "!has_resp"
        exec: $fallback
      - exec: $cloudflare