log:
  level: info
  production: true
plugins:
  - tag: handle_ecs
    type: ecs_handler
    args:
      forward: true
      send: true
      mask4: 32
      mask6: 48
  - tag: cn_domain
    type: domain_set
    args:
      files:
        - "./rules/china_domain_list.txt"
        - "./rules/cdn_domain_list.txt"
  - tag: cn_ip
    type: ip_set
    args:
      files:
        - "./rules/china_ip_list.txt"
  - tag: cf_ip
    type: ip_set
    args:
      ips:
        - 1.1.1.1
  - tag: global_dns
    type: forward
    args:
      concurrent: 2
      upstreams:
        - tag: "Google DOT"
          addr: 'tls://dns.google'
          dial_addr: 8.8.8.8
          enable_pipeline: true
        - tag: "Google DOT2"
          addr: "tls://dns.google"
          dial_addr: 8.8.4.4
          enable_pipeline: true
  - tag: cn_dns
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: "DNSPod"
          addr: 'tls://dot.pub'
          bootstrap: "223.5.5.5"
          enable_pipeline: true
        - tag: "AliDNS"
          addr: "https://dns.alidns.com/dns-query"
          bootstrap: "119.29.29.29"
  - tag: blacklist
    type: ip_set
    args:
      files:
        - ./rules/ip_blacklist.txt

  - tag: cloudflare_ip
    type: ip_set
    args:
      files:
        - ./rules/cf_ip4.txt
        - ./rules/cf_ip6.txt
  - tag: cloudflare
    type: sequence
    args:
      - matches:
        - "resp_ip $cloudflare_ip"
        - "qtype 1"
        exec: "black_hole $cf_ip4_prefer"
      - matches:
        - "resp_ip $cloudflare_ip"
        - "qtype 28"
        exec: "black_hole $cf_ip6_prefer" 
  - tag: cn_resolver
    type: sequence
    args:
      - exec: $cn_dns
      - matches:
        - "resp_ip $blacklist"
        exec: drop_resp
      - exec: query_summary $cn_dns
      - exec: accept
  - tag: global_resolver
    type: sequence
    args:
      - exec: $global_dns
      - matches:
        - "resp_ip $blacklist"
        exec: drop_resp
      - exec: query_summary $global_dns
  - tag: fallback
    type: fallback
    args:
      primary: cn_resolver
      secondary: global_resolver
      threshold: 20000
      always_standby: true
  - tag: main
    type: sequence
    args:
      - exec: $handle_ecs
      - exec: forward_edns0opt 10 15
      - matches:
        - qname $cn_domain
        exec: $cn_resolver
      - matches: has_resp
        exec: accept
      - exec: $global_resolver
      - matches:
        - resp_ip $cn_ip
        exec: $cn_resolver
      - matches: 
        - "!has_resp"
        exec: $fallback
      - exec: $cloudflare
  - tag: server
    type: "udp_server"
    args:
      entry: main
      listen: "[::]:53"

